import { CorporateFooter } from "./components/CorporateHomePage/CorporateFooter";
import { CorporateHeader } from "./components/CorporateHomePage/CorporateHeader";
import { CorporateNavigation } from "./components/CorporateHomePage/CorporateNavigation";
import { NavigationItem } from "./components/CorporateHomePage/CorporateNavigation/NavigationItem";
import { CorporateFooterNavigationMenu } from "./components/CorporateHomePage/CorporateFooter/CorporateFooterNavigationMenu"
import { CorporateServices } from "./components/CorporateHomePage/CorporateServices";
import { CorporateService } from "./components/CorporateHomePage/CorporateServices/CorporateService";
import { CorporateTestimonials } from "./components/CorporateHomePage/CorporateTestimonials";
import { CorporateTestimonial } from "./components/CorporateHomePage/CorporateTestimonials/CorporateTestimonial";
import { DarkProductHeadline } from "./components/ProductLandingPage/DarkProductHeadline";
import { LightProductHeadline } from "./components/ProductLandingPage/LightProductHeadline";
import { ProductFooter } from "./components/ProductLandingPage/productfooter";
import { ProductFooterNavigation } from "./components/ProductLandingPage/productfooter/ProductFooterNavigation";
import { SubMenuElement } from "./components/ProductLandingPage/ProductFooter/ProductFooterNavigation/ProductFooterNavigationElement/ProductFooterNavigationSubMenu/SubMenuElement";
import {ProductFooterNavigationSubMenu} from "./components/ProductLandingPage/ProductFooter/ProductFooterNavigation/ProductFooterNavigationElement/ProductFooterNavigationSubMenu";
import {ProductFooterNavigationElement} from "./components/ProductLandingPage/ProductFooter/ProductFooterNavigation/ProductFooterNavigationElement";
import { ProductHeadline } from "./components/ProductLandingPage/ProductHeadline";
import { ProductNavigation } from "./components/ProductLandingPage/ProductNavigation";
import { ProductMenuItem } from "./components/ProductLandingPage/ProductNavigation/ProductMenuItem";
import { ProductHeadlineContainer } from "./components/ProductLandingPage/ProductHeadlineContainer";